import { views } from "../components/views.js";
const app = document.querySelector("#app"), sectionName = document.querySelector("#sectionName"), sidebar = document.querySelector("#sidebar");
const names = {home:"Command Center",projects:"Projects",assistants:"AI Assistants",knowledge:"Knowledge Base",timeline:"Timeline",notes:"Notes",settings:"Settings"};
const defaults = [{id:"welcome", title:"Welcome to DexieOS", body:"A small thought to begin with: systems are here to make space for your best work."}];
const getNotes = () => JSON.parse(localStorage.getItem("dexieos-notes") || JSON.stringify(defaults));
const saveNotes = notes => localStorage.setItem("dexieos-notes", JSON.stringify(notes));
let activeNote = 0;
function setClock(){ const clock=document.querySelector("#clock"); if(clock) clock.firstChild.nodeValue=new Intl.DateTimeFormat("en-GB",{hour:"2-digit",minute:"2-digit",hour12:false}).format(new Date()); }
function applyDisplay(mode){ document.body.classList.toggle("dim-mode",mode==="dim"); localStorage.setItem("dexieos-display",mode); }
function renderNotes(){ const notes=getNotes(), list=document.querySelector("#noteList"), title=document.querySelector("#noteTitle"), body=document.querySelector("#noteBody"); if(!list) return; activeNote=Math.min(activeNote,notes.length-1); const note=notes[activeNote]; list.innerHTML=notes.map((n,i)=>`<button class="${i===activeNote?"active":""}" data-note="${i}"><b>${n.title||"Untitled note"}</b><small>${n.body||"No content"}</small></button>`).join(""); title.value=note.title; body.value=note.body; list.onclick=e=>{const button=e.target.closest("[data-note]");if(button){activeNote=+button.dataset.note;renderNotes();}}; const update=()=>{notes[activeNote]={...notes[activeNote],title:title.value,body:body.value};saveNotes(notes);document.querySelector("#saveStatus").textContent="Saved locally · just now";}; title.oninput=update;body.oninput=update;document.querySelector("#newNote").onclick=()=>{notes.unshift({id:Date.now(),title:"Untitled note",body:""});saveNotes(notes);activeNote=0;renderNotes();title.focus();}; }
function bindPage(page){ if(page==="home"){setClock();setInterval(setClock,1000);document.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>location.hash=b.dataset.go);} if(page==="notes")renderNotes(); if(page==="knowledge"){const search=document.querySelector("#knowledgeSearch");search.oninput=()=>document.querySelectorAll("[data-doc]").forEach(d=>d.hidden=!d.textContent.toLowerCase().includes(search.value.toLowerCase()));} if(page==="settings"){const root=document.documentElement; const stored=localStorage.getItem("dexieos-accent"); if(stored) root.style.setProperty("--accent",stored); document.querySelectorAll(".swatch").forEach(s=>{if(s.dataset.accent===stored){document.querySelector(".swatch.active")?.classList.remove("active");s.classList.add("active");}s.onclick=()=>{root.style.setProperty("--accent",s.dataset.accent);localStorage.setItem("dexieos-accent",s.dataset.accent);document.querySelector(".swatch.active")?.classList.remove("active");s.classList.add("active");};});const display=document.querySelector("#displayMode");display.value=localStorage.getItem("dexieos-display")||"dark";display.onchange=()=>applyDisplay(display.value);const sw=document.querySelector("#animationSwitch");sw.onclick=()=>{sw.classList.toggle("active");document.body.classList.toggle("reduced-motion",!sw.classList.contains("active"));localStorage.setItem("dexieos-motion",sw.classList.contains("active"));};if(localStorage.getItem("dexieos-motion")==="false"){sw.classList.remove("active");}} }
function route(){const page=(location.hash||"#home").slice(1);const view=views[page]||views.home;app.innerHTML=view();app.classList.remove("page-stage");void app.offsetWidth;app.classList.add("page-stage");sectionName.textContent=names[page]||names.home;document.querySelectorAll("[data-page]").forEach(a=>a.classList.toggle("active",a.dataset.page===page));sidebar.classList.remove("open");bindPage(page);}
document.querySelector("#menuButton").onclick=()=>sidebar.classList.toggle("open");document.querySelector("#themeToggle").onclick=()=>applyDisplay(document.body.classList.contains("dim-mode")?"dark":"dim");const savedDisplay=localStorage.getItem("dexieos-display");if(savedDisplay)applyDisplay(savedDisplay);if(localStorage.getItem("dexieos-motion")==="false")document.body.classList.add("reduced-motion");window.addEventListener("hashchange",route);route();
