import { documents,defaultTools } from "../js/data.js";import { read } from "../storage/store.js";
const h=(k,t,p,a="")=>`<section class="page-header"><div><p class="kicker">${k}</p><h1>${t}</h1><p>${p}</p></div>${a}</section>`;const empty=(text,action,label)=>`<section class="glass-card empty-state"><span>◎</span><h2>${text}</h2><p>Everything here is local to this browser.</p>${action?`<button class="primary-button" data-action="${action}">${label}</button>`:""}</section>`;
export const icon=name=>name?.slice(0,1)||"↗";
export const views={
home:()=>{const projects=read("projects",[]);return `${h("Personal operating system","Your command center.","Local tools, projects, and links — no simulated system activity.",`<div class="live-time" id="clock">--:--<small>LOCAL TIME · SOUTHAMPTON</small></div>`)}<div class="dashboard-grid"><div class="stack"><section class="glass-card welcome-card"><p class="kicker">DEXIEOS / LOCAL-FIRST</p><h2>Build your own workspace.</h2><p>Add projects, useful links, and tools that belong in your day.</p></section><section class="glass-card"><div class="card-heading"><h2>Quick launch</h2><button class="text-button" data-action="add-link">+ Add link</button></div><div class="launch-grid" id="shortcutGrid"></div></section><section class="glass-card"><div class="card-heading"><h2>Projects</h2><button class="text-button" data-action="add-project">+ New project</button></div><div class="project-list" id="homeProjects">${projects.length?"":"<p class=empty-files>No projects yet. Add a project and choose its status.</p>"}</div></section></div><div class="stack"><section class="glass-card"><div class="card-heading"><h2>Weather</h2><button class="text-button" data-action="weather-city">Change city</button></div><div class="weather" id="weatherCard"><span class="weather-icon">◌</span><span><b>Southampton</b><small>Loading live weather…</small></span></div><div class="quick-actions"><button class="quick-action" data-action="enable-weather"><span>⌖</span>Use my location</button><button class="quick-action" data-action="weather-city"><span>⌕</span>Choose city</button></div></section><section class="glass-card"><div class="card-heading"><h2>Quick actions</h2></div><div class="quick-actions"><button class="quick-action" data-go="projects"><span>◈</span>Projects</button><button class="quick-action" data-go="assistants"><span>✦</span>AI Toolkit</button><button class="quick-action" data-go="notes"><span>▤</span>Notes</button><button class="quick-action" data-go="files"><span>▱</span>Files</button></div></section></div></div>`},
projects:()=>`${h("Workspace","Projects","Create local project records. Nothing is added until you add it.",`<button class="primary-button" data-action="add-project">+ New project</button>`)}<div class="project-grid" id="projectGrid"></div>`,
assistants:()=>`${h("Useful tools","AI Toolkit","Direct links to tools you use, stored locally.",`<button class="primary-button" data-action="add-tool">+ Add tool</button>`)}<div class="assistant-grid" id="toolGrid"></div>`,
knowledge:()=>`${h("Second brain","Knowledge Base","Search and read the local library.")}<section class="knowledge-layout"><aside class="knowledge-sidebar"><label class="search"><span>⌕</span><input id="knowledgeSearch" placeholder="Search library"></label><div class="knowledge-list">${documents.map(d=>`<button>${d}</button>`).join("")}</div></aside><article class="markdown"><h2>Welcome to DexieOS</h2><p>Keep durable context here. Use Notes for drafts and capture.</p></article></section>`,
timeline:()=>`${h("Trajectory","Timeline","Add milestones to your local roadmap.",`<button class="primary-button" data-action="add-milestone">+ Add milestone</button>`)}<section class="timeline" id="timeline"></section>`,
notes:()=>`${h("Scratchpad","Notes","Private local notes.",`<button class="primary-button" id="newNote">+ New note</button>`)}<section class="notes-layout"><aside class="notes-sidebar"><div class="note-list" id="noteList"></div></aside><section class="note-editor"><input class="note-title" id="noteTitle" placeholder="Untitled note"><textarea class="note-body" id="noteBody" placeholder="Start writing…"></textarea><p class="save-status">Saved locally</p></section></section>`,
files:()=>`${h("Local workspace","Files","Manage a folder through your browser’s File System Access API.")}<section class="files-panel glass-card"><div class="drop-zone"><strong>Choose a workspace folder from this browser.</strong><span>File access is available on supported secure contexts.</span></div></section>`,
settings:()=>`${h("Personalize","Settings","Preferences remain in this browser.")}<section class="settings-grid"><article class="setting-row glass-card"><span><h2>Display mode</h2><p>Choose your interface mode.</p></span><select id="displayMode"><option value="dark">Dark</option><option value="light">Light</option><option value="dim">Dim</option></select></article><article class="setting-row glass-card"><span><h2>Timezone</h2><p>Automatic detection is used until you select a fallback.</p></span><select id="timezoneSelect"></select></article><article class="setting-row glass-card"><span><h2>Google account integration</h2><p>Requires Google OAuth configuration and is not enabled yet.</p></span><button class="text-button" disabled>Unavailable</button></article><article class="setting-row glass-card"><span><h2>Reset DexieOS</h2><p>Clear local tools, links, projects, and preferences.</p></span><button class="text-button danger" id="resetSettings">Reset</button></article></section>`};
export { defaultTools };
